"""add chunk embeddings

Revision ID: 9ff6c171b3e8
Revises: dadd3b0b82c1
Create Date: 2026-09-14 16:47:42.688297

"""
from typing import Sequence, Union
import pgvector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff6c171b3e8'
down_revision: Union[str, Sequence[str], None] = 'dadd3b0b82c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_chunks', 'embedding')
    # ### end Alembic commands ###
